# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GlobalRefreshTimeValue.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'GlobalRefreshTimeValue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cGlobalRefreshTimeValue.proto\x12\x08protobuf\"g\n\x16GlobalRefreshTimeValue\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12\x0c\n\x04time\x18\x03 \x01(\x03\x12\r\n\x05param\x18\x04 \x01(\t\x12\x12\n\nnew_status\x18\x05 \x01(\x03\x42\x1d\n\x1bnet.im30.aps.model.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GlobalRefreshTimeValue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033net.im30.aps.model.protobuf'
  _globals['_GLOBALREFRESHTIMEVALUE']._serialized_start=42
  _globals['_GLOBALREFRESHTIMEVALUE']._serialized_end=145
# @@protoc_insertion_point(module_scope)
